### PR TITLE
RT#102626: proper fix for t/parent-pmc.t

### PR DESCRIPTION
**Pull request by dolmen**
A failing case of t/parent-pmc.t was remaining: perl < 5.14 with PERL_DISABLE_PMC in build options. This patch fixes this issue. We check for PERL_DISABLE_PMC using Config::Perl::V if available.
This module is added as a 'recommends' test dependency in Makefile.PL. If the dependency is missing or if PERL_DISABLE_PMC is set we skip the test. On smokers ($ENV{SMOKE_TESTING}=1 and $] < 5.14) we make the dependency mandatory.

### CODE REVIEW

**Comment by dolmen** [comment]
Cc: @wolfsage

**Comment by dolmen** [comment]
GitHub says my branch has been merged, but I don't see the commits in the history or in the last release.
What happened?

**Comment by Corion** [comment]
Hello Olivier,

Am 01.04.2015 um 23:39 schrieb Olivier Mengué:> GitHub says my branch 
has been merged, but I don't see the commits in

> the history or in the last release.
> What happened?

the branch was merged,  but then I force-pushed a different bugfix that 
needed to go into 5.21.10, and by then Github had deleted your bugfix so 
that I couldn't rebase/reapply it :-/ I think I replicated your change 
but your author attribution was lost...

-max

**Comment by dolmen** [comment]
Please review this pull request again (if ever you reviewed it once) because the patches it includes are not in the history at all. My patch uses Config::Perl::V to detect if PMC are disabled.

**Comment by dolmen** [comment]
#5 is a lighter alternative.

**Comment by dolmen** [comment]
Note however that my patch preserves the full intent of 125e9a5625b7facbcd36de288d9b4479b257ade2, even for older perls, thanks to Config::Perl::V.

**Pull request merged**
